name: todoist-readme

on:
  workflow_dispatch:
  schedule:
    # Runs every minute
    - cron: "* * * * *"

jobs:
  update-readme:
    name: Update todoist stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
     # - uses: seyed-mohammadreza-mousavi/seyed-mohammadreza-mousavi.git@main
      - uses: seyed-mohammadreza-mousavi/seyed-mohammadreza-mousavi/.github/workflows/todoist-readme@main
        with:
    #      Default: ${{ github.repository }}
#          repository: seyed-mohammadreza-mousavi/seyed-mohammadreza-mousavi.git
          token: ${{ secrets.TODOISTAPI }}

