name: todoist-readme

on:
  workflow_dispatch:
  schedule:
    # Runs every minute
    - cron: "* * * * *"

jobs:
  update-readme:
    name: Update todoist stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
#      - uses: seyed-mohammadreza-mousavi/seyed-mohammadreza-mousavi/.github/actions/workflows/todoist-readme@main
        with:
          repository: seyed-mohammadreza-mousavi/seyed-mohammadreza-mousavi.git
          token: ${{ secrets.TODOISTAPI }}
