name: todoist-readme

on:
  workflow_dispatch:
  schedule:
    # Runs every minute
    - cron: "* * * * *"

jobs:
  update-readme:
    name: Update todoist stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          TODOIST_API_KEY: ${{ secrets.TODOIST_API_KEY }}
