name: Todoist Readme

on:
  workflow_dispatch:
  schedule:
    # Runs every minute
    - cron: "* * * * *"

jobs:
  update-readme:
    name: Update todoist stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: seyed-mohammadreza-mousavi/todoist-readme@master
        with:
          TODOIST_API_KEY: ${{ secrets.1dc2b9fe4d9d9df16044ee1bd6fdc821837a039a }}
          PREMIUM: ""
